_BASE_: "Base-RCNN-FPN.yaml"
OUTPUT_DIR: "./output/cpn_0000/"
MODEL:
  META_ARCHITECTURE: "ConPropNetProposalNetwork"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "ConPropNetRPN"
  RPN:
    POST_NMS_TOPK_TEST: 2000
