_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR : "./output/ret0024"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  LOAD_PROPOSALS: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1230
    SCORE_THRESH_TEST: 0.0001
  PROPOSAL_GENERATOR:
    NAME: "PrecomputedProposals"
DATASETS:
  TRAIN: ("lvis_v0.5_train",)
  PROPOSAL_FILES_TRAIN: ("./datasets/detectron2/proposals/ret0018_0089999_coco_trn_box_proposals.pkl", )
  TEST: ("lvis_v0.5_val",)
  PROPOSAL_FILES_TEST: ("./datasets/detectron2/proposals/ret0018_0089999_coco_val_box_proposals.pkl", )
DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 2
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
