_BASE_: "../Base-RetinaNet.yaml"
OUTPUT_DIR : "./output/ret0008_lvis"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RETINANET:
    NUM_CLASSES: 1230
#    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v0.5_train",)
  TEST: ("lvis_v0.5_val",)
#TEST:
#  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
#DATALOADER:
#  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
#  REPEAT_THRESHOLD: 0.001
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (12000, 160000)
  MAX_ITER: 1800000
