_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR: "./output/ret0027b"
MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RPN:
    POST_NMS_TOPK_TEST: 2000
    BATCH_SIZE_PER_IMAGE: 1024
DATASETS:
  TRAIN: ("lvis_v0.5_train",)
  TEST: ("lvis_v0.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
