_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR : "./output/inference_ret0017/model_0089999_lvis_val/"
MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
  WEIGHTS: "./output/ret/ret0017/model_0089999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RPN:
    POST_NMS_TOPK_TEST: 2000
DATASETS:
  TEST: ("lvis_v0.5_val",)    # ("coco_2017_train",)
