_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR: "./output/inference_ret0018/model_0089999_cocotrn/"
MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
  WEIGHTS: "./output/ret/ret0018/model_0089999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RPN:
    POST_NMS_TOPK_TEST: 2000
DATASETS:
  TEST: ("coco_2017_train",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
