_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR : "./output/inference_ret0016/model_0089999/"
MODEL:
  WEIGHTS: "./output/ret0016/model_0089999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1230
    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v0.5_train",)
  TEST: ("lvis_v0.5_val",)
SOLVER:
  BASE_LR: 0.002              # Default is 0.02. Drop by 10 to learn gently...!       
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
