_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR: "./output/inference_ret0020b"
MODEL:
  WEIGHTS: "./output/ret0020b/model_0089999.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
