_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR: "./output/inference/ret0018_fewer"
MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
  WEIGHTS: "./output/ret/ret0018/model_0089999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RPN:
    NMS_THRESH: 0.25
    POST_NMS_TOPK_TEST: 20        # Original was 2000. This is for visualization.
DATASETS:
  TRAIN: ("lvis_v0.5_train",)
  TEST: ("lvis_v0.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
