_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR: "./output/inference_cpn_0000/"
MODEL:
  META_ARCHITECTURE: "ConPropNetProposalNetwork"
  WEIGHTS: "./output/cpn_0000/model_0089999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "ConPropNetRPN"
  RPN:
    POST_NMS_TOPK_TEST: 2000
