_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR: "./output/inference_cpn_0001/"
MODEL:
  META_ARCHITECTURE: "ConPropNetProposalNetwork"
  WEIGHTS: "./output/cpn_0001/model_0089999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "ConPropNetRPN"
  RPN:
    POST_NMS_TOPK_TEST: 2000
DATASETS:
  TRAIN: ("lvis_v0.5_train",)
  TEST: ("lvis_v0.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
