_BASE_: "../Base-RetinaNet.yaml"
OUTPUT_DIR : "./output/ret_ows01"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RETINANET:
    NUM_CLASSES: 1230               # Default: 80
    SCORE_THRESH_TEST: 0.0001       
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v0.5_train",)
  TEST: ("lvis_v0.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
  NUM_WORKERS: 2              # Default is 4. But, jobs keep crashing. So, set to 2.
SOLVER:
  IMS_PER_BATCH: 4            # Now, working with 1 per GPU and 4 GPUs.
  BASE_LR: 0.0005             # Default for 1 img/GPU and 8 GPUS is 0.005
  STEPS: (12000, 160000)
  MAX_ITER: 18000000          # 100x than actual experiment. Like OWS.
  CHECKPOINT_PERIOD: 500000   # Only checkpoint every 500,000 iterations.
