_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR : "./output/ows/ows05"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1230
    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v0.5_train",)
  TEST: ("lvis_v0.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300   # LVIS allows up to 300
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
  NUM_WORKERS: 2              # Default is 4. But, jobs keep crashing. So, set to 2.
SOLVER:
  IMS_PER_BATCH: 16           # Default is 2 img/GPU and 8 GPUs. Now, do 4img/GPU and 4 GPUs.
  BASE_LR: 0.02               # Default for 2 img/GPU and 8 GPUS is 0.01
  STEPS: (6000, 80000)
  MAX_ITER: 9000000           # 100x than actual experiment.
  CHECKPOINT_PERIOD: 500000   # Only checkpoint every 500,000 iterations.SOLVER:
